-- Generated schema documentation comments
-- Created by schema_documenter tool

BEGIN TRANSACTION;

-- Table: bdline_ua_lep_diss_tbl
COMMENT ON TABLE mca_env_base.bdline_ua_lep_diss_tbl IS 'WECA LEP (including North Somerset) boundary';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_diss_tbl.name IS 'Name';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_diss_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_diss_tbl.id IS 'Id';

-- Table: bdline_ua_lep_tbl
COMMENT ON TABLE mca_env_base.bdline_ua_lep_tbl IS 'WECA LEP UA unitary authority boundaries';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_tbl.name IS 'Name';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_tbl.code IS 'Code';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.bdline_ua_lep_tbl.id IS 'Id';

-- Table: bdline_ua_weca_diss_tbl
COMMENT ON TABLE mca_env_base.bdline_ua_weca_diss_tbl IS 'WECA dissolved boundary';
COMMENT ON COLUMN mca_env_base.bdline_ua_weca_diss_tbl.name IS 'Name';
COMMENT ON COLUMN mca_env_base.bdline_ua_weca_diss_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.bdline_ua_weca_diss_tbl.id IS 'Id';

-- Table: bdline_ward_lep_tbl
COMMENT ON TABLE mca_env_base.bdline_ward_lep_tbl IS 'Ward boundaries for UA in WECA LEP';
COMMENT ON COLUMN mca_env_base.bdline_ward_lep_tbl.name IS 'Name';
COMMENT ON COLUMN mca_env_base.bdline_ward_lep_tbl.file_name IS 'File name';
COMMENT ON COLUMN mca_env_base.bdline_ward_lep_tbl.code IS 'Code';
COMMENT ON COLUMN mca_env_base.bdline_ward_lep_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.bdline_ward_lep_tbl.id IS 'Id';

-- Table: boundary_lookup_tbl
COMMENT ON TABLE mca_env_base.boundary_lookup_tbl IS 'Boundary lookup table';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.pcd7 IS 'Postcode 7 characters';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.pcd8 IS 'Postcode 8 characters';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.pcds IS 'Postcode with space';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.dointr IS 'Date of introduction';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.doterm IS 'Date of termination';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.usertype IS 'User type';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.oa21cd IS 'Output area 2021';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.lsoa21cd IS 'LSOA code 2021';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.msoa21cd IS 'MSOA code 2021';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.ladcd IS 'Local Authority District code';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.lsoa21nm IS 'LSOA name 2021';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.msoa21nm IS 'MSOA name 2021';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.ladnm IS 'Local Authority District name';
COMMENT ON COLUMN mca_env_base.boundary_lookup_tbl.ladnmw IS 'Local Authority District name Welsh';

-- Table: ca_boundaries_bgc_tbl
COMMENT ON TABLE mca_env_base.ca_boundaries_bgc_tbl IS 'Combined authority boundaries england UK';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.FID IS 'Fid';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.CAUTH25CD IS 'Combined authority code 2025';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.CAUTH25NM IS 'Combined authority name 2025';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.BNG_E IS 'Easting';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.BNG_N IS 'Northing';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.LONG IS 'Longitude';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.LAT IS 'Latitude';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.Shape__Area IS 'Shape area';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.Shape__Length IS 'Shape length';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.GlobalID IS 'Globalid';
COMMENT ON COLUMN mca_env_base.ca_boundaries_bgc_tbl.geom IS 'Geometry';

-- Table: ca_la_lookup_tbl
COMMENT ON TABLE mca_env_base.ca_la_lookup_tbl IS 'Combined authority local authority boundaries';
COMMENT ON COLUMN mca_env_base.ca_la_lookup_tbl.LAD25CD IS 'Local authority district code 2025';
COMMENT ON COLUMN mca_env_base.ca_la_lookup_tbl.LAD25NM IS 'Local authority district name 2025';
COMMENT ON COLUMN mca_env_base.ca_la_lookup_tbl.CAUTH25CD IS 'Combined authority code 2025';
COMMENT ON COLUMN mca_env_base.ca_la_lookup_tbl.CAUTH25NM IS 'Combined authority name 2025';
COMMENT ON COLUMN mca_env_base.ca_la_lookup_tbl.ObjectId IS 'Objectid';

-- Table: codepoint_open_lep_tbl
COMMENT ON TABLE mca_env_base.codepoint_open_lep_tbl IS 'Codepoint open postcode LEP';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.postcode IS 'UK postal code';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.pc_nospace IS 'Pc nospace';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.admin_district_code IS 'Admin district code';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.admin_ward_code IS 'Admin ward code';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.xco IS 'Easting';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.yco IS 'Northing';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.lon IS 'Longitude';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.lat IS 'Latitude';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.codepoint_open_lep_tbl.id IS 'Id';

-- Table: eng_lsoa_imd_tbl
COMMENT ON TABLE mca_env_base.eng_lsoa_imd_tbl IS 'Indices of multiple deprivation England LSOA';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.lsoa21_code IS 'Lsoa21 code';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.imd_decile IS 'Imd decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.income_decile IS 'Income decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.employment_decile IS 'Employment decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.education_decile IS 'Education decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.health_decile IS 'Health decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.crime_decile IS 'Crime decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.housing_and_services_decile IS 'Housing and services decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.environment_decile IS 'Environment decile';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.imd_rank IS 'Imd rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.income_rank IS 'Income rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.employment_rank IS 'Employment rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.education_rank IS 'Education rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.health_rank IS 'Health rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.crime_rank IS 'Crime rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.housing_and_services_rank IS 'Housing and services rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.environment_rank IS 'Environment rank';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.imd_score IS 'Imd score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.income_score IS 'Income score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.employment_score IS 'Employment score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.education_score IS 'Education score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.health_score IS 'Health score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.crime_score IS 'Crime score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.housing_and_services_score IS 'Housing and services score';
COMMENT ON COLUMN mca_env_base.eng_lsoa_imd_tbl.environment_score IS 'Environment score';

-- Table: la_ghg_emissions_tbl
COMMENT ON TABLE mca_env_base.la_ghg_emissions_tbl IS 'Local authority greenhouse gas emissions (long format)';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.country IS 'Country';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.country_code IS 'Country code';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.region IS 'Region';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.region_code IS 'Region code';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.second_tier_authority IS 'Second tier authority';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.local_authority IS 'Local authority';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.local_authority_code IS 'Local authority code';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.calendar_year IS 'Calendar year';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.la_ghg_sector IS 'La ghg sector';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.la_ghg_subsector IS 'La ghg subsector';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.greenhouse_gas IS 'Greenhouse gas';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.territorial_emissions_kt_co2e IS 'Territorial emissions kt co2e';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.emissions_within_the_scope_of_influence_of_las_kt_co2 IS 'Emissions within the scope of influence of las kt co2';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.midyear_population_thousands IS 'Midyear population thousands';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_tbl.area_km2 IS 'Area km2';

-- Table: la_ghg_emissions_wide_tbl
COMMENT ON TABLE mca_env_base.la_ghg_emissions_wide_tbl IS 'Local authority greenhouse gas emissions (wide format)';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.regioncountry IS 'Regioncountry';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.second_tier_authority IS 'Second tier authority';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.local_authority IS 'Local authority';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.local_authority_code IS 'Local authority code';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.calendar_year IS 'Calendar year';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.industry_electricity IS 'Industry electricity';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.industry_gas IS 'Industry gas';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.large_industrial_installations IS 'Large industrial installations';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.industry_other IS 'Industry other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.industry_total IS 'Industry total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.commercial_electricity IS 'Commercial electricity';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.commercial_gas IS 'Commercial gas';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.commercial_other IS 'Commercial other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.commercial_total IS 'Commercial total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.public_sector_electricity IS 'Public sector electricity';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.public_sector_gas IS 'Public sector gas';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.public_sector_other IS 'Public sector other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.public_sector_total IS 'Public sector total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.domestic_electricity IS 'Domestic electricity';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.domestic_gas IS 'Domestic gas';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.domestic_other IS 'Domestic other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.domestic_total IS 'Domestic total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.road_transport_a_roads IS 'Road transport a roads';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.road_transport_motorways IS 'Road transport motorways';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.road_transport_minor_roads IS 'Road transport minor roads';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.diesel_railways IS 'Diesel railways';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.transport_other IS 'Transport other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.transport_total IS 'Transport total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_forestry IS 'Net emissions forestry';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_cropland_mineral_soils_change IS 'Net emissions cropland mineral soils change';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_grassland_mineral_soils_change IS 'Net emissions grassland mineral soils change';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_settlements IS 'Net emissions settlements';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_peatland IS 'Net emissions peatland';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_bioenergy_crops IS 'Net emissions bioenergy crops';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.net_emissions_other_lulucf IS 'Net emissions other lulucf';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.lulucf_net_emissions IS 'Lulucf net emissions';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.agriculture_electricity IS 'Agriculture electricity';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.agriculture_gas IS 'Agriculture gas';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.agriculture_other IS 'Agriculture other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.agriculture_livestock IS 'Agriculture livestock';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.agriculture_soils IS 'Agriculture soils';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.agriculture_total IS 'Agriculture total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.landfill IS 'Landfill';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.waste_other IS 'Waste other';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.waste_total IS 'Waste total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.grand_total IS 'Grand total';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.population_000s_midyear_estimate IS 'Population 000s midyear estimate';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.per_capita_emissions_t_co2e IS 'Per capita emissions t co2e';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.area_km2 IS 'Area km2';
COMMENT ON COLUMN mca_env_base.la_ghg_emissions_wide_tbl.emissions_per_km2_kt_co2e IS 'Emissions per km2 kt co2e';

-- Table: lsoa_2021_lep_tbl
COMMENT ON TABLE mca_env_base.lsoa_2021_lep_tbl IS 'Table containing 5 columns';
COMMENT ON COLUMN mca_env_base.lsoa_2021_lep_tbl.lsoa21cd IS 'LSOA code 2021';
COMMENT ON COLUMN mca_env_base.lsoa_2021_lep_tbl.lsoa21nm IS 'LSOA name 2021';
COMMENT ON COLUMN mca_env_base.lsoa_2021_lep_tbl.area_m2 IS 'Area m2';
COMMENT ON COLUMN mca_env_base.lsoa_2021_lep_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.lsoa_2021_lep_tbl.id IS 'Id';

-- Table: open_uprn_lep_tbl
COMMENT ON TABLE mca_env_base.open_uprn_lep_tbl IS 'UPRN LEP';
COMMENT ON COLUMN mca_env_base.open_uprn_lep_tbl.uprn IS 'Unique Property Reference Number';
COMMENT ON COLUMN mca_env_base.open_uprn_lep_tbl.x_coordinate IS 'X coordinate';
COMMENT ON COLUMN mca_env_base.open_uprn_lep_tbl.y_coordinate IS 'Y coordinate';
COMMENT ON COLUMN mca_env_base.open_uprn_lep_tbl.shape IS 'Spatial geometry';
COMMENT ON COLUMN mca_env_base.open_uprn_lep_tbl.id IS 'Id';

-- Table: postcode_centroids_tbl
COMMENT ON TABLE mca_env_base.postcode_centroids_tbl IS 'Postcode centroids UK';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.x IS 'Easting';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.y IS 'Northing';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.pcd7 IS 'Postcode 7 characters';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.pcd8 IS 'Postcode 8 characters';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.pcds IS 'Postcode with space';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.dointr IS 'Date of introduction';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.doterm IS 'Date of termination';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.cty25cd IS 'County code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ced25cd IS 'County electoral division 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lad25cd IS 'Local authority disctrict code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.wd25cd IS 'Ward code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.parncp25cd IS 'Parish and non civil parished area code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.usrtypind IS 'Postcode User Type';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.east1m IS 'Easting to 1m';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.north1m IS 'Northing to 1m';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.gridind IS 'Grid Reference Positional Quality Indicator';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.hlth19cd IS 'Former health authority code';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.nhser24cd IS 'NHS England region code 2024';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ctry25cd IS 'Country code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.rgn25cd IS 'Region code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ssr95cd IS 'Standard statistical region code 1995';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.pcon24cd IS 'Westminster parliamentary constituency code 2024';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.eer20cd IS 'European electoral region code 2020';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.educ23cd IS 'Education code 2023';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ttwa15cd IS 'Travel to work area code 2015';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.pco19cd IS 'Primary care organisation code 2019';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.itl25cd IS 'International territorial level code 2025';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.wdstl05cd IS 'Statistical ward code 2005';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.oa01cd IS 'Output area code 2001';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.wdcas03cd IS 'CAS ward code 2003';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.npark16cd IS 'National park code 2016';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lsoa01cd IS 'Lower layer super output area 2001';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.msoa01cd IS 'Medium layer super output area 2001';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ruc01ind IS 'Rural urban classification indicator 2001';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.oac01ind IS 'Output area classiciation indicator 2001';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.oa11cd IS 'Output area code 2011';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lsoa11cd IS 'Lower level super output area 2011';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.msoa11cd IS 'Medium layer super output area 2011';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.wz11cd IS 'Workplace Zone 2011';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.sicbl24cd IS 'Sub ICB locations code 2024';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.bua24cd IS 'Built up areas code 2024';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ruc11ind IS 'Rural urban classification code 2011';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.oac11ind IS 'Output area classification indicator 2011';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lat IS 'Latitude';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.long IS 'Longitude';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lep21cd1 IS 'Local enterprise partnership code 2021 1st instance';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lep21cd2 IS 'Local enterprise partnership code 2021 2nd instance';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.pfa23cd IS 'Police force area code 2023';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.imd20ind IS 'Indices of multiple deprivation indicator 2020';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.cal24cd IS 'Cancer alliance code 2024';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.icb23cd IS 'Integrated care board code 2023';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.oa21cd IS 'Output area code 2021';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.lsoa21cd IS 'Lower layer super output area code 2021';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.msoa21cd IS 'Medium layer super output area code 2021';
COMMENT ON COLUMN mca_env_base.postcode_centroids_tbl.ruc21ind IS 'Rural urban classification indicator 2021';

-- Table: uk_lsoa_tenure_tbl
COMMENT ON TABLE mca_env_base.uk_lsoa_tenure_tbl IS 'Table containing 5 columns';
COMMENT ON COLUMN mca_env_base.uk_lsoa_tenure_tbl.lsoa21_code IS 'Lower layer super output area code 2021';
COMMENT ON COLUMN mca_env_base.uk_lsoa_tenure_tbl.n IS 'Number of households';
COMMENT ON COLUMN mca_env_base.uk_lsoa_tenure_tbl.prop IS 'Proportion of households';

-- Table: raw_domestic_epc_certificates_tbl
COMMENT ON TABLE mca_env_base.raw_domestic_epc_certificates_tbl IS 'Table containing 93 columns';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LMK_KEY IS 'Lodgement Management Key';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ADDRESS1 IS 'Address1';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ADDRESS2 IS 'Address2';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ADDRESS3 IS 'Address3';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.POSTCODE IS 'UK postal code';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.BUILDING_REFERENCE_NUMBER IS 'Building reference number';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CURRENT_ENERGY_RATING IS 'Current value of energy rating';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.POTENTIAL_ENERGY_RATING IS 'Potential value of energy rating';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CURRENT_ENERGY_EFFICIENCY IS 'Current value of energy efficiency';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.POTENTIAL_ENERGY_EFFICIENCY IS 'Potential value of energy efficiency';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.PROPERTY_TYPE IS 'Property type';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.BUILT_FORM IS 'Built form';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.INSPECTION_DATE IS 'Date of inspection date';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LOCAL_AUTHORITY IS 'Local authority';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CONSTITUENCY IS 'Parliamentary constituency';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.COUNTY IS 'County';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LODGEMENT_DATE IS 'Date of lodgement date';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.TRANSACTION_TYPE IS 'Transaction type';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ENVIRONMENT_IMPACT_CURRENT IS 'Environment impact current';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ENVIRONMENT_IMPACT_POTENTIAL IS 'Environment impact potential';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ENERGY_CONSUMPTION_CURRENT IS 'Energy consumption current';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ENERGY_CONSUMPTION_POTENTIAL IS 'Energy consumption potential';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CO2_EMISSIONS_CURRENT IS 'Co2 emissions current';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CO2_EMISS_CURR_PER_FLOOR_AREA IS 'Co2 emiss curr per floor area';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CO2_EMISSIONS_POTENTIAL IS 'Co2 emissions potential';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LIGHTING_COST_CURRENT IS 'Lighting cost current';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LIGHTING_COST_POTENTIAL IS 'Lighting cost potential';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HEATING_COST_CURRENT IS 'Heating cost current';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HEATING_COST_POTENTIAL IS 'Heating cost potential';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HOT_WATER_COST_CURRENT IS 'Hot water cost current';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HOT_WATER_COST_POTENTIAL IS 'Hot water cost potential';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.TOTAL_FLOOR_AREA IS 'Total floor area';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ENERGY_TARIFF IS 'Energy tariff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINS_GAS_FLAG IS 'Mains gas flag (y/n)';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLOOR_LEVEL IS 'Floor level';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLAT_TOP_STOREY IS 'Flat top storey';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLAT_STOREY_COUNT IS 'Flat storey count';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAIN_HEATING_CONTROLS IS 'Main heating controls';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MULTI_GLAZE_PROPORTION IS 'Multi glaze proportion';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.GLAZED_TYPE IS 'Glazed type';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.GLAZED_AREA IS 'Glazed area';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.EXTENSION_COUNT IS 'Extension count';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.NUMBER_HABITABLE_ROOMS IS 'Number habitable rooms';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.NUMBER_HEATED_ROOMS IS 'Number heated rooms';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LOW_ENERGY_LIGHTING IS 'Low energy lighting';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.NUMBER_OPEN_FIREPLACES IS 'Number open fireplaces';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HOTWATER_DESCRIPTION IS 'Hotwater description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HOT_WATER_ENERGY_EFF IS 'Hot water energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HOT_WATER_ENV_EFF IS 'Hot water env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLOOR_DESCRIPTION IS 'Floor description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLOOR_ENERGY_EFF IS 'Floor energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLOOR_ENV_EFF IS 'Floor env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WINDOWS_DESCRIPTION IS 'Windows description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WINDOWS_ENERGY_EFF IS 'Windows energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WINDOWS_ENV_EFF IS 'Windows env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WALLS_DESCRIPTION IS 'Walls description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WALLS_ENERGY_EFF IS 'Walls energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WALLS_ENV_EFF IS 'Walls env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.SECONDHEAT_DESCRIPTION IS 'Secondheat description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.SHEATING_ENERGY_EFF IS 'Sheating energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.SHEATING_ENV_EFF IS 'Sheating env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ROOF_DESCRIPTION IS 'Roof description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ROOF_ENERGY_EFF IS 'Roof energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ROOF_ENV_EFF IS 'Roof env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINHEAT_DESCRIPTION IS 'Mainheat description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINHEAT_ENERGY_EFF IS 'Mainheat energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINHEAT_ENV_EFF IS 'Mainheat env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINHEATCONT_DESCRIPTION IS 'Mainheatcont description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINHEATC_ENERGY_EFF IS 'Mainheatc energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAINHEATC_ENV_EFF IS 'Mainheatc env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LIGHTING_DESCRIPTION IS 'Lighting description';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LIGHTING_ENERGY_EFF IS 'Lighting energy eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LIGHTING_ENV_EFF IS 'Lighting env eff';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MAIN_FUEL IS 'Main fuel';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.WIND_TURBINE_COUNT IS 'Wind turbine count';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.HEAT_LOSS_CORRIDOR IS 'Heat loss corridor';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.UNHEATED_CORRIDOR_LENGTH IS 'Unheated corridor length';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FLOOR_HEIGHT IS 'Floor height';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.PHOTO_SUPPLY IS 'Photo supply';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.SOLAR_WATER_HEATING_FLAG IS 'Solar water heating flag (y/n)';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.MECHANICAL_VENTILATION IS 'Mechanical ventilation';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.ADDRESS IS 'Full address';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LOCAL_AUTHORITY_LABEL IS 'Local authority label';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CONSTITUENCY_LABEL IS 'Constituency label';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.POSTTOWN IS 'Post town';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.CONSTRUCTION_AGE_BAND IS 'Construction age band';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LODGEMENT_DATETIME IS 'Timestamp for lodgement datetime';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.TENURE IS 'Tenure';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.FIXED_LIGHTING_OUTLETS_COUNT IS 'Fixed lighting outlets count';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.LOW_ENERGY_FIXED_LIGHT_COUNT IS 'Low energy fixed light count';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.UPRN IS 'Unique Property Reference Number';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.UPRN_SOURCE IS 'Uprn source';
COMMENT ON COLUMN mca_env_base.raw_domestic_epc_certificates_tbl.REPORT_TYPE IS 'Report type';

-- Table: raw_non_domestic_epc_certificates_tbl
COMMENT ON TABLE mca_env_base.raw_non_domestic_epc_certificates_tbl IS 'Table containing 41 columns';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.LMK_KEY IS 'Lodgement Management Key';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ADDRESS1 IS 'Address1';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ADDRESS2 IS 'Address2';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ADDRESS3 IS 'Address3';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.POSTCODE IS 'UK postal code';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.BUILDING_REFERENCE_NUMBER IS 'Building reference number';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ASSET_RATING IS 'Asset rating';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ASSET_RATING_BAND IS 'Asset rating band';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.PROPERTY_TYPE IS 'Property type';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.INSPECTION_DATE IS 'Date of inspection date';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.LOCAL_AUTHORITY IS 'Local authority';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.CONSTITUENCY IS 'Parliamentary constituency';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.COUNTY IS 'County';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.LODGEMENT_DATE IS 'Date of lodgement date';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.TRANSACTION_TYPE IS 'Transaction type';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.NEW_BUILD_BENCHMARK IS 'New build benchmark';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.EXISTING_STOCK_BENCHMARK IS 'Existing stock benchmark';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.BUILDING_LEVEL IS 'Building level';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.MAIN_HEATING_FUEL IS 'Main heating fuel';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.OTHER_FUEL_DESC IS 'Other fuel description';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.SPECIAL_ENERGY_USES IS 'Special energy uses';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.RENEWABLE_SOURCES IS 'Renewable sources';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.FLOOR_AREA IS 'Floor area';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.STANDARD_EMISSIONS IS 'Standard emissions';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.TARGET_EMISSIONS IS 'Target emissions';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.TYPICAL_EMISSIONS IS 'Typical emissions';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.BUILDING_EMISSIONS IS 'Building emissions';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.AIRCON_PRESENT IS 'Aircon present';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.AIRCON_KW_RATING IS 'Aircon kw rating';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ESTIMATED_AIRCON_KW_RATING IS 'Estimated aircon kw rating';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.AC_INSPECTION_COMMISSIONED IS 'Ac inspection commissioned';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.BUILDING_ENVIRONMENT IS 'Building environment';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.ADDRESS IS 'Full address';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.LOCAL_AUTHORITY_LABEL IS 'Local authority label';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.CONSTITUENCY_LABEL IS 'Constituency label';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.POSTTOWN IS 'Post town';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.LODGEMENT_DATETIME IS 'Lodgement datetime';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.PRIMARY_ENERGY_VALUE IS 'Primary energy value';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.UPRN IS 'Unique Property Reference Number';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.UPRN_SOURCE IS 'Uprn source';
COMMENT ON COLUMN mca_env_base.raw_non_domestic_epc_certificates_tbl.REPORT_TYPE IS 'Report type';

-- Views

-- View: ca_la_ghg_emissions_sub_sector_ods_vw
COMMENT ON TABLE mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw IS 'View based on la_ghg_emissions_tbl, joined_data;, ca_la_lookup_inc_ns_vw';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.region_code IS 'Region code';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.local_authority IS 'Local authority';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.local_authority_code IS 'Local authority code';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.calendar_year IS 'Calendar year';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.la_ghg_sector IS 'La ghg sector';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.la_ghg_subsector IS 'La ghg subsector';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.greenhouse_gas IS 'Greenhouse gas';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.territorial_emissions_kt_co2e IS 'Territorial emissions kt co2e';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.emissions_within_the_scope_of_influence_of_las_kt_co2 IS 'Emissions within the scope of influence of las kt co2';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.midyear_population_thousands IS 'Midyear population thousands';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.area_km2 IS 'Area km2';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.cauthcd IS 'Cauthcd';
COMMENT ON COLUMN mca_env_base.ca_la_ghg_emissions_sub_sector_ods_vw.cauthnm IS 'Cauthnm';

-- View: epc_domestic_vw
COMMENT ON TABLE mca_env_base.epc_domestic_vw IS 'View based on raw_domestic_epc_certificates_tbl';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LMK_KEY IS 'Lodgement Management Key';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ADDRESS1 IS 'Address1';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ADDRESS2 IS 'Address2';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ADDRESS3 IS 'Address3';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.POSTCODE IS 'UK postal code';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.BUILDING_REFERENCE_NUMBER IS 'Building reference number';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CURRENT_ENERGY_RATING IS 'Current value of energy rating';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.POTENTIAL_ENERGY_RATING IS 'Potential value of energy rating';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CURRENT_ENERGY_EFFICIENCY IS 'Current value of energy efficiency';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.POTENTIAL_ENERGY_EFFICIENCY IS 'Potential value of energy efficiency';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.PROPERTY_TYPE IS 'Property type';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.BUILT_FORM IS 'Built form';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.INSPECTION_DATE IS 'Date of inspection date';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LOCAL_AUTHORITY IS 'Local authority';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CONSTITUENCY IS 'Parliamentary constituency';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.COUNTY IS 'County';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LODGEMENT_DATE IS 'Date of lodgement date';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.TRANSACTION_TYPE IS 'Transaction type';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ENVIRONMENT_IMPACT_CURRENT IS 'Environment impact current';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ENVIRONMENT_IMPACT_POTENTIAL IS 'Environment impact potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ENERGY_CONSUMPTION_CURRENT IS 'Energy consumption current';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ENERGY_CONSUMPTION_POTENTIAL IS 'Energy consumption potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CO2_EMISSIONS_CURRENT IS 'Co2 emissions current';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CO2_EMISS_CURR_PER_FLOOR_AREA IS 'Co2 emiss curr per floor area';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CO2_EMISSIONS_POTENTIAL IS 'Co2 emissions potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LIGHTING_COST_CURRENT IS 'Lighting cost current';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LIGHTING_COST_POTENTIAL IS 'Lighting cost potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HEATING_COST_CURRENT IS 'Heating cost current';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HEATING_COST_POTENTIAL IS 'Heating cost potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HOT_WATER_COST_CURRENT IS 'Hot water cost current';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HOT_WATER_COST_POTENTIAL IS 'Hot water cost potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.TOTAL_FLOOR_AREA IS 'Total floor area';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ENERGY_TARIFF IS 'Energy tariff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINS_GAS_FLAG IS 'Mains gas flag (y/n)';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLOOR_LEVEL IS 'Floor level';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLAT_TOP_STOREY IS 'Flat top storey';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLAT_STOREY_COUNT IS 'Flat storey count';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAIN_HEATING_CONTROLS IS 'Main heating controls';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MULTI_GLAZE_PROPORTION IS 'Multi glaze proportion';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.GLAZED_TYPE IS 'Glazed type';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.GLAZED_AREA IS 'Glazed area';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.EXTENSION_COUNT IS 'Extension count';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.NUMBER_HABITABLE_ROOMS IS 'Number habitable rooms';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.NUMBER_HEATED_ROOMS IS 'Number heated rooms';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LOW_ENERGY_LIGHTING IS 'Low energy lighting';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.NUMBER_OPEN_FIREPLACES IS 'Number open fireplaces';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HOTWATER_DESCRIPTION IS 'Hotwater description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HOT_WATER_ENERGY_EFF IS 'Hot water energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HOT_WATER_ENV_EFF IS 'Hot water env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLOOR_DESCRIPTION IS 'Floor description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLOOR_ENERGY_EFF IS 'Floor energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLOOR_ENV_EFF IS 'Floor env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WINDOWS_DESCRIPTION IS 'Windows description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WINDOWS_ENERGY_EFF IS 'Windows energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WINDOWS_ENV_EFF IS 'Windows env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WALLS_DESCRIPTION IS 'Walls description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WALLS_ENERGY_EFF IS 'Walls energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WALLS_ENV_EFF IS 'Walls env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.SECONDHEAT_DESCRIPTION IS 'Secondheat description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.SHEATING_ENERGY_EFF IS 'Sheating energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.SHEATING_ENV_EFF IS 'Sheating env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ROOF_DESCRIPTION IS 'Roof description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ROOF_ENERGY_EFF IS 'Roof energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ROOF_ENV_EFF IS 'Roof env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINHEAT_DESCRIPTION IS 'Mainheat description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINHEAT_ENERGY_EFF IS 'Mainheat energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINHEAT_ENV_EFF IS 'Mainheat env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINHEATCONT_DESCRIPTION IS 'Mainheatcont description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINHEATC_ENERGY_EFF IS 'Mainheatc energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAINHEATC_ENV_EFF IS 'Mainheatc env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LIGHTING_DESCRIPTION IS 'Lighting description';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LIGHTING_ENERGY_EFF IS 'Lighting energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LIGHTING_ENV_EFF IS 'Lighting env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MAIN_FUEL IS 'Main fuel';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.WIND_TURBINE_COUNT IS 'Wind turbine count';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.HEAT_LOSS_CORRIDOR IS 'Heat loss corridor';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.UNHEATED_CORRIDOR_LENGTH IS 'Unheated corridor length';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FLOOR_HEIGHT IS 'Floor height';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.PHOTO_SUPPLY IS 'Photo supply';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.SOLAR_WATER_HEATING_FLAG IS 'Solar water heating flag (y/n)';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.MECHANICAL_VENTILATION IS 'Mechanical ventilation';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.ADDRESS IS 'Full address';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LOCAL_AUTHORITY_LABEL IS 'Local authority label';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CONSTITUENCY_LABEL IS 'Constituency label';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.POSTTOWN IS 'Post town';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CONSTRUCTION_AGE_BAND IS 'Construction age band';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LODGEMENT_DATETIME IS 'Timestamp for lodgement datetime';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.TENURE IS 'Tenure';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.FIXED_LIGHTING_OUTLETS_COUNT IS 'Fixed lighting outlets count';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LOW_ENERGY_FIXED_LIGHT_COUNT IS 'Low energy fixed light count';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.UPRN IS 'Unique Property Reference Number';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.UPRN_SOURCE IS 'Uprn source';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.REPORT_TYPE IS 'Report type';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.NOMINAL_CONSTRUCTION_YEAR IS 'Computed field: NOMINAL_CONSTRUCTION_YEAR';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.CONSTRUCTION_EPOCH IS 'Computed field: CONSTRUCTION_EPOCH';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.TENURE_CLEAN IS 'Computed field: TENURE_CLEAN';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LODGEMENT_YEAR IS 'Computed field: LODGEMENT_YEAR';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LODGEMENT_MONTH IS 'Computed field: LODGEMENT_MONTH';
COMMENT ON COLUMN mca_env_base.epc_domestic_vw.LODGEMENT_DAY IS 'Computed field: LODGEMENT_DAY';

-- View: epc_non_domestic_lep_vw
COMMENT ON TABLE mca_env_base.epc_non_domestic_lep_vw IS 'View based on raw_non_domestic_epc_certificates_tbl, open_uprn_lep_tbl';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.LMK_KEY IS 'Lodgement Management Key';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ADDRESS1 IS 'Address1';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ADDRESS2 IS 'Address2';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ADDRESS3 IS 'Address3';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.POSTCODE IS 'UK postal code';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.BUILDING_REFERENCE_NUMBER IS 'Building reference number';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ASSET_RATING IS 'Asset rating';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ASSET_RATING_BAND IS 'Asset rating band';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.PROPERTY_TYPE IS 'Property type';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.INSPECTION_DATE IS 'Date of inspection date';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.LOCAL_AUTHORITY IS 'Local authority';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.CONSTITUENCY IS 'Parliamentary constituency';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.COUNTY IS 'County';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.LODGEMENT_DATE IS 'Date of lodgement date';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.TRANSACTION_TYPE IS 'Transaction type';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.NEW_BUILD_BENCHMARK IS 'New build benchmark';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.EXISTING_STOCK_BENCHMARK IS 'Existing stock benchmark';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.BUILDING_LEVEL IS 'Building level';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.MAIN_HEATING_FUEL IS 'Main heating fuel';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.OTHER_FUEL_DESC IS 'Other fuel description';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.SPECIAL_ENERGY_USES IS 'Special energy uses';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.RENEWABLE_SOURCES IS 'Renewable sources';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.FLOOR_AREA IS 'Floor area';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.STANDARD_EMISSIONS IS 'Standard emissions';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.TARGET_EMISSIONS IS 'Target emissions';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.TYPICAL_EMISSIONS IS 'Typical emissions';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.BUILDING_EMISSIONS IS 'Building emissions';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.AIRCON_PRESENT IS 'Aircon present';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.AIRCON_KW_RATING IS 'Aircon kw rating';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ESTIMATED_AIRCON_KW_RATING IS 'Estimated aircon kw rating';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.AC_INSPECTION_COMMISSIONED IS 'Ac inspection commissioned';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.BUILDING_ENVIRONMENT IS 'Building environment';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.ADDRESS IS 'Full address';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.LOCAL_AUTHORITY_LABEL IS 'Local authority label';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.CONSTITUENCY_LABEL IS 'Constituency label';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.POSTTOWN IS 'Post town';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.LODGEMENT_DATETIME IS 'Lodgement datetime';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.PRIMARY_ENERGY_VALUE IS 'Primary energy value';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.UPRN IS 'Unique Property Reference Number';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.UPRN_SOURCE IS 'Uprn source';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.REPORT_TYPE IS 'Report type';
COMMENT ON COLUMN mca_env_base.epc_non_domestic_lep_vw.geo_point_2d IS 'Geo point 2d';

-- View: epc_domestic_lep_vw
COMMENT ON TABLE mca_env_base.epc_domestic_lep_vw IS 'View based on epc_domestic_vw, open_uprn_lep_tbl';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LMK_KEY IS 'Lodgement Management Key';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.BUILDING_REFERENCE_NUMBER IS 'Building reference number';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CURRENT_ENERGY_RATING IS 'Current value of energy rating';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.POTENTIAL_ENERGY_RATING IS 'Potential value of energy rating';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CURRENT_ENERGY_EFFICIENCY IS 'Current value of energy efficiency';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.POTENTIAL_ENERGY_EFFICIENCY IS 'Potential value of energy efficiency';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.PROPERTY_TYPE IS 'Property type';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.BUILT_FORM IS 'Built form';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.INSPECTION_DATE IS 'Date of inspection date';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LOCAL_AUTHORITY IS 'Local authority';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CONSTITUENCY IS 'Parliamentary constituency';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.COUNTY IS 'County';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LODGEMENT_DATE IS 'Date of lodgement date';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.TRANSACTION_TYPE IS 'Transaction type';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ENVIRONMENT_IMPACT_CURRENT IS 'Environment impact current';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ENVIRONMENT_IMPACT_POTENTIAL IS 'Environment impact potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ENERGY_CONSUMPTION_CURRENT IS 'Energy consumption current';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ENERGY_CONSUMPTION_POTENTIAL IS 'Energy consumption potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CO2_EMISSIONS_CURRENT IS 'Co2 emissions current';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CO2_EMISS_CURR_PER_FLOOR_AREA IS 'Co2 emiss curr per floor area';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CO2_EMISSIONS_POTENTIAL IS 'Co2 emissions potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LIGHTING_COST_CURRENT IS 'Lighting cost current';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LIGHTING_COST_POTENTIAL IS 'Lighting cost potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HEATING_COST_CURRENT IS 'Heating cost current';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HEATING_COST_POTENTIAL IS 'Heating cost potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HOT_WATER_COST_CURRENT IS 'Hot water cost current';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HOT_WATER_COST_POTENTIAL IS 'Hot water cost potential';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.TOTAL_FLOOR_AREA IS 'Total floor area';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ENERGY_TARIFF IS 'Energy tariff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINS_GAS_FLAG IS 'Mains gas flag (y/n)';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLOOR_LEVEL IS 'Floor level';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLAT_TOP_STOREY IS 'Flat top storey';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLAT_STOREY_COUNT IS 'Flat storey count';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAIN_HEATING_CONTROLS IS 'Main heating controls';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MULTI_GLAZE_PROPORTION IS 'Multi glaze proportion';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.GLAZED_TYPE IS 'Glazed type';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.GLAZED_AREA IS 'Glazed area';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.EXTENSION_COUNT IS 'Extension count';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.NUMBER_HABITABLE_ROOMS IS 'Number habitable rooms';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.NUMBER_HEATED_ROOMS IS 'Number heated rooms';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LOW_ENERGY_LIGHTING IS 'Low energy lighting';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.NUMBER_OPEN_FIREPLACES IS 'Number open fireplaces';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HOTWATER_DESCRIPTION IS 'Hotwater description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HOT_WATER_ENERGY_EFF IS 'Hot water energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HOT_WATER_ENV_EFF IS 'Hot water env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLOOR_DESCRIPTION IS 'Floor description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLOOR_ENERGY_EFF IS 'Floor energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLOOR_ENV_EFF IS 'Floor env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WINDOWS_DESCRIPTION IS 'Windows description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WINDOWS_ENERGY_EFF IS 'Windows energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WINDOWS_ENV_EFF IS 'Windows env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WALLS_DESCRIPTION IS 'Walls description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WALLS_ENERGY_EFF IS 'Walls energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WALLS_ENV_EFF IS 'Walls env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.SECONDHEAT_DESCRIPTION IS 'Secondheat description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.SHEATING_ENERGY_EFF IS 'Sheating energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.SHEATING_ENV_EFF IS 'Sheating env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ROOF_DESCRIPTION IS 'Roof description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ROOF_ENERGY_EFF IS 'Roof energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.ROOF_ENV_EFF IS 'Roof env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINHEAT_DESCRIPTION IS 'Mainheat description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINHEAT_ENERGY_EFF IS 'Mainheat energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINHEAT_ENV_EFF IS 'Mainheat env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINHEATCONT_DESCRIPTION IS 'Mainheatcont description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINHEATC_ENERGY_EFF IS 'Mainheatc energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAINHEATC_ENV_EFF IS 'Mainheatc env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LIGHTING_DESCRIPTION IS 'Lighting description';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LIGHTING_ENERGY_EFF IS 'Lighting energy eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LIGHTING_ENV_EFF IS 'Lighting env eff';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MAIN_FUEL IS 'Main fuel';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.WIND_TURBINE_COUNT IS 'Wind turbine count';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.HEAT_LOSS_CORRIDOR IS 'Heat loss corridor';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.UNHEATED_CORRIDOR_LENGTH IS 'Unheated corridor length';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FLOOR_HEIGHT IS 'Floor height';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.PHOTO_SUPPLY IS 'Photo supply';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.SOLAR_WATER_HEATING_FLAG IS 'Solar water heating flag (y/n)';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.MECHANICAL_VENTILATION IS 'Mechanical ventilation';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LOCAL_AUTHORITY_LABEL IS 'Local authority label';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CONSTITUENCY_LABEL IS 'Constituency label';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.POSTTOWN IS 'Post town';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CONSTRUCTION_AGE_BAND IS 'Construction age band';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LODGEMENT_DATETIME IS 'Timestamp for lodgement datetime';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.TENURE IS 'Tenure';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.FIXED_LIGHTING_OUTLETS_COUNT IS 'Fixed lighting outlets count';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LOW_ENERGY_FIXED_LIGHT_COUNT IS 'Low energy fixed light count';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.UPRN IS 'Unique Property Reference Number';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.UPRN_SOURCE IS 'Uprn source';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.REPORT_TYPE IS 'Report type';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.NOMINAL_CONSTRUCTION_YEAR IS 'Computed field: NOMINAL_CONSTRUCTION_YEAR';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.CONSTRUCTION_EPOCH IS 'Computed field: CONSTRUCTION_EPOCH';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.TENURE_CLEAN IS 'Computed field: TENURE_CLEAN';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LODGEMENT_YEAR IS 'Computed field: LODGEMENT_YEAR';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LODGEMENT_MONTH IS 'Computed field: LODGEMENT_MONTH';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.LODGEMENT_DAY IS 'Computed field: LODGEMENT_DAY';
COMMENT ON COLUMN mca_env_base.epc_domestic_lep_vw.geo_point_2d IS 'Geo point 2d';


COMMIT;