-- Bronze Layer: Index of Deprivation (IoD) 2025 Loading
-- Purpose: Load IoD 2025 File 7 with all ranks, scores, deciles, and population denominators
-- Source: DLUHC IoD 2025 File 7 (manual download)
-- Geography: England LSOAs (2021 boundaries)
-- Table Created: iod2025_tbl

CREATE OR REPLACE TABLE iod2025_tbl AS
SELECT
    "LSOA code (2021)" AS lsoa_cd,
    "LSOA name (2021)" AS lsoa_nm,
    "Local Authority District code (2024)" AS la_cd,
    "Local Authority District name (2024)" AS la_nm,
    "Index of Multiple Deprivation (IMD) Score" AS imd_score,
    "Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)" AS imd_rank,
    "Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)" AS imd_decile,
    "Income Score (rate)" AS income_score,
    "Income Rank (where 1 is most deprived)" AS income_rank,
    "Income Decile (where 1 is most deprived 10% of LSOAs)" AS income_decile,
    "Employment Score (rate)" AS employment_score,
    "Employment Rank (where 1 is most deprived)" AS employment_rank,
    "Employment Decile (where 1 is most deprived 10% of LSOAs)" AS employment_decile,
    "Education, Skills and Training Score" AS education_score,
    "Education, Skills and Training Rank (where 1 is most deprived)" AS education_rank,
    "Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)" AS education_decile,
    "Health Deprivation and Disability Score" AS health_score,
    "Health Deprivation and Disability Rank (where 1 is most deprived)" AS health_rank,
    "Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)" AS health_decile,
    "Crime Score" AS crime_score,
    "Crime Rank (where 1 is most deprived)" AS crime_rank,
    "Crime Decile (where 1 is most deprived 10% of LSOAs)" AS crime_decile,
    "Barriers to Housing and Services Score" AS barriers_score,
    "Barriers to Housing and Services Rank (where 1 is most deprived)" AS barriers_rank,
    "Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)" AS barriers_decile,
    "Living Environment Score" AS living_env_score,
    "Living Environment Rank (where 1 is most deprived)" AS living_env_rank,
    "Living Environment Decile (where 1 is most deprived 10% of LSOAs)" AS living_env_decile,
    "Income Deprivation Affecting Children Index (IDACI) Score (rate)" AS idaci_score,
    "Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)" AS idaci_rank,
    "Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)" AS idaci_decile,
    "Income Deprivation Affecting Older People (IDAOPI) Score (rate)" AS idaopi_score,
    "Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived)" AS idaopi_rank,
    "Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)" AS idaopi_decile,
    "Children and Young People Sub-domain Score" AS cyp_sub_score,
    "Children and Young People Sub-domain Rank (where 1 is most deprived)" AS cyp_sub_rank,
    "Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSO" AS cyp_sub_decile,
    "Adult Skills Sub-domain Score" AS adult_skills_sub_score,
    "Adult Skills Sub-domain Rank (where 1 is most deprived)" AS adult_skills_sub_rank,
    "Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs)" AS adult_skills_sub_decile,
    "Geographical Barriers Sub-domain Score" AS geo_barriers_sub_score,
    "Geographical Barriers Sub-domain Rank (where 1 is most deprived)" AS geo_barriers_sub_rank,
    "Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)" AS geo_barriers_sub_decile,
    "Wider Barriers Sub-domain Score" AS wider_barriers_sub_score,
    "Wider Barriers Sub-domain Rank (where 1 is most deprived)" AS wider_barriers_sub_rank,
    "Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)" AS wider_barriers_sub_decile,
    "Indoors Sub-domain Score" AS indoors_sub_score,
    "Indoors Sub-domain Rank (where 1 is most deprived)" AS indoors_sub_rank,
    "Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)" AS indoors_sub_decile,
    "Outdoors Sub-domain Score" AS outdoors_sub_score,
    "Outdoors Sub-domain Rank (where 1 is most deprived)" AS outdoors_sub_rank,
    "Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)" AS outdoors_sub_decile,
    "Total population: mid 2022" AS total_pop,
    "Dependent Children aged 0-15: mid 2022" AS children_pop,
    "Older population aged 60 and over: mid 2022" AS older_pop,
    "Working age population 18-66 (for use with Employment Deprivation Domain): mid 2022" AS working_age_pop
FROM read_csv('data_lake/landing/manual/File_7_IoD2025_All_Ranks_Scores_Deciles_Population_Denominators.csv');
